[package]
name = "scan-internet"
version = "0.1.0"
authors = ["Oleg Loutchansky <luchansodev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
